port: /dev/neo-s300-1
baud: 500000
inverted: false
frame_id: /laserscanner_front_link
scan_id: 8
scan_intervals: [[-1.4835298641952, 1.4835298641952]] #[rad] these intervals are included to the scan +-85°
