<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="mp500lwa4d" >
  <xacro:include filename="$(find mp500lwa4d_description)/urdf/lwa4dmp500.gazebo"/>
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="safety_offset" value="0.02"/>
  <xacro:include filename="$(find mp500lwa4d_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find mp500lwa4d_description)/urdf/common.xacro"/>

<!-- Materials -->



  <!--neo_mp_500-->
  <!--xacro:include filename="$(find neo_mp_500)/robot_model/mp_500/mp500.urdf.xacro" /-->

<!--++++++++++++++++++++++++++++++base_link++++++++++++++++++++++++++++++++++++++++++++++++++++--> 
<!--++++++++++++++++++++body++++++++++++++++++++++++++++--> 
  <link name="base_link">
    <inertial>
      <mass value="25.67" />
      <origin xyz="0 0 0.216" rpy="0 0 0"/>
      <inertia ixx="0.54" ixy="0.0" ixz="0.0" iyy="1.08" iyz="0.0" izz="1.23" />
    </inertial>
    <visual name='body'>
      <!--origin xyz="0.0 0.0 0.234" rpy="0 0 1.57" /--><!-- for cylinder -->
      <origin xyz="-0.160 0.0 0.09" rpy="0 0 -1.57" /><!-- for STL -->
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/MP500-BODY.STL" scale="0.01 0.01 0.01"/>
        <!--cylinder length="0.381" radius="0.2545"/-->
        <!--box size="0.445 0.277 0.17"/-->
      </geometry>
      <material name="Neobotix/Grey" />
    </visual>
    <collision name='body_collision'>
      <origin xyz="0 0 0.216" rpy="0 0 -1.57" />
      <geometry>
        <box size="0.400 0.676 0.300"/>
        <!--cylinder length="0.381" radius="0.2545"/-->
      </geometry>
    </collision>
  </link>

  <link name="mobile_dummy_link">
  </link>

  <joint name="mobile_dummy_joint" type="fixed">
    <parent link="base_link"/>
    <child link="mobile_dummy_link"/>
    <origin xyz="0 0 0"/>
  </joint>

<!--+++++++++++++++++++wheel_left_link++++++++++++++++++++++++--> 
  <link name="wheel_left_link" type="wheel">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.0078125" iyz="0" izz="0.0045" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 -1.57" />
      <geometry>
	<mesh filename="package://mp500lwa4d_description/meshes/MP500-WHEEL.STL" scale="0.01 0.01 0.01" /> 
      </geometry>
      <material name="Neobotix/Black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.57 -1.57" />
      <geometry>
        <cylinder radius="0.125" length="0.085"/>
      </geometry>
    </collision>
			
  </link>

<!--+++++++++++++++++++wheel_left_joint++++++++++++++++++++++++--> 
  <joint name="wheel_left_joint" type="revolute">
    <origin xyz="-0.155 0.255 0.13" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-1e+16" upper="1e+16" velocity="5"/>
    <joint_properties damping="0.0" friction="0.0" />
    <parent link="base_link" />
    <child link="wheel_left_link" />
  </joint>

<!--+++++++++++++++++++wheel_right_link++++++++++++++++++++++++--> 
  <link name="wheel_right_link" type="wheel">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <!--inertia ixx="0.0051" ixy="0" ixz="0" iyy="0.0051" iyz="0" izz="0.009" /-->
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.0078125" iyz="0" izz="0.0045" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 -1.57" />
      <geometry>
	<mesh filename="package://mp500lwa4d_description/meshes/MP500-WHEEL.STL" scale="0.01 0.01 0.01" />
      </geometry>
      <material name="Neobotix/Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.57 -1.57" />
      <geometry>
	<cylinder radius="0.125" length="0.085"/>
      </geometry>
    </collision>
  </link>

<!--+++++++++++++++++++wheel_right_joint++++++++++++++++++++++++--> 
  <joint name="wheel_right_joint" type="revolute">
    <origin xyz="-0.155 -0.255 0.13" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-1e+16" upper="1e+16" velocity="5"/>
    <joint_properties damping="0.0" friction="0.0" />
    <parent link="base_link" />
    <child link="wheel_right_link" />
  </joint>


<!--+++++++++++++++++++laserscanner_front_joint++++++++++++++++++++++++--> 
  <joint name="laserscanner_front_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="-0.39 0 0.281" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="laserscanner_front_link"/>
  </joint>

<!--+++++++++++++++++++laserscanner_front_link++++++++++++++++++++++++-->
  <link name="laserscanner_front_link" type="laser">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" rpy="3.14 0 -1.57" />
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
    </inertial>
    <visual>
      <origin xyz="0 0 -0.04" rpy="3.14 0 -1.57" />
      <geometry>
        <!--cylinder length="0.154" radius="0.053" /-->		  		
        <mesh filename="package://mp500lwa4d_description/meshes/SICK-S300.STL" />
      </geometry>
      <material name="Neobotix/Yellow"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="3.14 0 -1.57" />
      <geometry>
	<cylinder length="0.154" radius="0.053" />
      </geometry>
    </collision>
  </link>
<!--+++++++++++++++ wheel_hanger+++++++++++++++++++++++++++-->
  <link name="hanger">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.00013" ixy="0" ixz="0" iyy="0.00013" iyz="0" izz="0.00013" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 -1.57" />
      <geometry>
	<mesh filename="package://mp500lwa4d_description/meshes/HANGER-WHEEL.STL" scale="0.01 0.01 0.01" />
      </geometry>
      <material name="Neobotix/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 -1.57" />
      <geometry>
        <sphere radius="0.00115"/>
      </geometry>
    </collision>
  </link>

  <joint name="hanger_joint" type="fixed">
    <origin xyz="0.255 0 0.11" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-1e+16" upper="1e+16" velocity="13.5"/>
    <joint_properties damping="0.0" friction="0.0" />
    <parent link="base_link" />
    <child link="hanger" />
  </joint>

<!--+++++++++++++++ castor_front +++++++++++++++++++++++++++-->
  <link name="castor_front">
    <!--inertial>
      <mass value="0.25" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.000025" ixy="0" ixz="0" iyy="0.000025" iyz="0" izz="0.000025" />
    </inertial-->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.005"/>    
      </geometry>
      <material name="Neobotix/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
    </collision>
  </link>
  
  <gazebo reference="caster_front">
    <mu1 value="0" />
    <mu2 value="0" />
    <kp  value="1.0" />
    <kd  value="1.0" />
  </gazebo>


  <joint name="castor_front_joint" type="fixed">
    <origin xyz="0.32 0 0.01" rpy="0 0 0"/>
     <!--limit effort="100.0" velocity="13.5"/>
    <joint_properties damping="0.0" friction="0.0" /-->
    <parent link="base_link" />
    <child link="castor_front" />
  </joint>


  <!--xacro:include filename="$(find schunk_description)/urdf/common.xacro" /-->
  <!--xacro:include filename="$(find schunk_description)/urdf/materials.urdf.xacro" /-->



  <!-- schunk lwa4d -->
  <!--xacro:include filename="$(find schunk_description)/urdf/lwa4d/lwa4d.urdf.xacro" /-->

  <!--xacro:include filename="$(find schunk_description)/urdf/common.xacro" /-->
  <!--xacro:include filename="$(find schunk_description)/urdf/lwa4d/lwa4d.gazebo.xacro"/-->
  <!--xacro:include filename="$(find schunk_description)/urdf/lwa4d/lwa4d.transmission.xacro"/-->

  <!-- joint between base_link and lwa4p_extended_connector_link -->
  <joint name="arm_podest_joint" type="fixed">
    <origin xyz="0.19 0 0.36" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="arm_podest_link"/>
  </joint>

  <link name="arm_podest_link">
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0091" ixy="0.0" ixz="0.0" iyy="0.0091" iyz="0.0" izz="0.0049" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_podest_link.stl"/>
      </geometry>
      <material name="Schunk/LightGrey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_podest_link.stl"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_base_joint" type="fixed">
   <origin xyz="0 0 0.140" rpy="0 0 0" />
   <axis xyz="0 0 1"/>
   <parent link="arm_podest_link"/>
   <child link="arm_base_link"/>
  </joint>

  <link name="arm_base_link">
    <!--xacro:default_inertial/-->
    <inertial>
      <mass value="0.02" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
    </inertial>
  </link>

  <!-- joint between arm_base_link and arm_1_link -->
  <joint name="arm_1_joint" type="revolute">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <parent link="arm_base_link"/>
    <child link="arm_1_link"/>
    <limit effort="216" velocity="0.4363" lower="${-M_PI+safety_offset}" upper="${M_PI-safety_offset}"/>
  </joint>
<!-- arm_1_link-->
  <link name="arm_1_link">
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0091" ixy="0.0" ixz="0.0" iyy="0.0091" iyz="0.0" izz="0.005" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_1_link.stl"/>
      </geometry>
      <material name="Schunk/LightGrey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_1_link.stl"/>
      </geometry>
    </collision>
  </link>

<!-- joint between arm_1_link and arm_2_link -->
  <joint name="arm_2_joint" type="revolute">
    <origin xyz="0 0 0.24" rpy="-${M_PI/2} -${M_PI/2} 0"/>
    <axis xyz="0 0 1"/>
    <parent link="arm_1_link"/>
    <child link="arm_2_link"/>
    <limit effort="216" velocity="0.43633" lower="${-2.14 + safety_offset}" upper="${2.14 - safety_offset}"/>
  </joint>
<!-- arm_2_link -->
  <link name="arm_2_link">
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0091" ixy="0.0" ixz="0.0" iyy="0.0049" iyz="0.0" izz="0.0091" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_2_link.stl"/>
      </geometry>
      <material name="Schunk/Black"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_2_link_collision.stl"/>
      </geometry>
    </collision>
  </link>

<!-- joint between arm_2_link and arm_3_link -->
  <joint name="arm_3_joint" type="revolute">
    <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    <axis xyz="0 0 1"/>
    <parent link="arm_2_link"/>
    <child link="arm_3_link"/>
    <limit effort="81.5" velocity="0.4186" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
  </joint>
<!-- arm_3_link -->
  <link name="arm_3_link">
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0091" ixy="0.0" ixz="0.0" iyy="0.0091" iyz="0.0" izz="0.0049" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_3_link.stl"/>
      </geometry>
      <material name="Schunk/LightGrey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_3_link_collision.stl"/>
      </geometry>
    </collision>
  </link>

<!-- joint between arm_3_link and arm_4_link -->
  <joint name="arm_4_joint" type="revolute">
    <origin xyz="0 0 0.328" rpy="-${M_PI/2} -${M_PI/2} 0"/>
    <axis xyz="0 0 1"/>
    <parent link="arm_3_link"/>
    <child link="arm_4_link"/>
    <limit effort="81.5" velocity="0.4186" lower="${-2.18 + safety_offset}" upper="${2.18 - safety_offset}"/>
  </joint>
<!--arm_4_link -->
  <link name="arm_4_link">
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0091" ixy="0.0" ixz="0.0" iyy="0.0049" iyz="0.0" izz="0.0091" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_4_link.stl"/>
      </geometry>
      <material name="Schunk/Black"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_4_link_collision.stl"/>
      </geometry>
    </collision>
  </link>

<!-- joint between arm_4_link and arm_5_link -->
  <joint name="arm_5_joint" type="revolute">
    <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    <axis xyz="0 0 1"/>
    <parent link="arm_4_link"/>
    <child link="arm_5_link"/>
    <limit effort="20.7" velocity="0.4363" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
  </joint>
<!-- arm_5_link -->
  <link name="arm_5_link">
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0091" ixy="0.0" ixz="0.0" iyy="0.0049" iyz="0.0" izz="0.0091" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_5_link.stl"/>
      </geometry>
      <material name="Schunk/LightGrey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_5_link_collision.stl"/>
      </geometry>
    </collision>
  </link>

<!-- joint between arm_5_link and arm_6_link -->
  <joint name="arm_6_joint" type="revolute">
    <origin xyz="0 0 0.323" rpy="-${M_PI/2} -${M_PI/2} 0"/>
    <axis xyz="0 0 1"/>
    <parent link="arm_5_link"/>
    <child link="arm_6_link"/>
    <limit effort="20.7" velocity="0.4363" lower="${-2.09 + safety_offset}" upper="${2.09 - safety_offset}"/>
  </joint>
<!-- arm_6_link -->
  <link name="arm_6_link">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.00196" ixy="0.0" ixz="0.0" iyy="0.00196" iyz="0.0" izz="0.00196" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_6_link.stl"/>
      </geometry>
      <material name="Schunk/Black"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_6_link_collision.stl"/>
      </geometry>
    </collision>
  </link>

<!-- joint between arm_6_link and arm_7_link -->
  <joint name="arm_7_joint" type="revolute">
    <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    <axis xyz="0 0 1"/>
    <parent link="arm_6_link"/>
    <child link="arm_7_link"/>
    <limit effort="4.5" velocity="0.9072" lower="${-2.96 + safety_offset}" upper="${2.96 - safety_offset}"/>
  </joint>
<!--arm_7_link -->
  <link name="arm_7_link">
    <inertial>
      <mass value="0.5" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_7_link.stl"/>
      </geometry>
      <material name="Schunk/LightGrey"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://mp500lwa4d_description/meshes/arm_7_link.stl"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_ee_joint" type="fixed">
    <origin xyz="0 0 0.0824" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="arm_7_link"/>
    <child link="arm_ee_link"/>
  </joint>

  <link name="arm_ee_link">
    <inertial>
      <mass value="0.01" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.00005" ixy="0.0" ixz="0.0" iyy="0.00005" iyz="0.0" izz="0.00005" />
    </inertial>
  </link>

<gazebo>
  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <robotNamespace>/</robotNamespace>		  
    <alwaysOn>true</alwaysOn>
    <updateRate>100</updateRate>
    <leftJoint>wheel_left_joint</leftJoint>
    <rightJoint>wheel_right_joint</rightJoint>
    <wheelSeparation>0.51</wheelSeparation>
    <wheelDiameter>0.125</wheelDiameter>
    <torque>11.4</torque>  <!-- 0.95*12-->
    <commandTopic>/mobile_base_controller/cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>map</odometryFrame>
    <robotBaseFrame>/base_link</robotBaseFrame>    
    <legacyMode>false</legacyMode>
    <rosDebugLevel>Debug</rosDebugLevel>
    <publishWheelTF>true</publishWheelTF>
    <publishWheelJointState>true</publishWheelJointState>
    <wheelAcceleration>0.5</wheelAcceleration>
    <wheelTorque>11.4</wheelTorque>
    <publishTf>1</publishTf>
    <odometrySource>encoder</odometrySource>
  </plugin>

<!--+++++++++++++++ in My Modell +++++++++++++++++++++++++++-->
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>mp500lwa4d</robotNamespace>
    <filterJointsParam>joint_names</filterJointsParam>
  </plugin>


</gazebo>


</robot>
